<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>MapFlux.Pagination</PackageId>
    <Version>1.0.0</Version>
    <Authors>kadirdemirkaya</Authors>
    <Description>
      Pagination + object mapping for .NET, powered by MapFlux.
    </Description>
    <PackageTags>pagination;mapping;mapflux;ef-core;dotnet</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MapFlux" Version="1.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>
</Project>
